# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
