# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('porabaapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='porabaapp.Car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='ime',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name=django.utils.timezone.now),
        ),
    ]
