# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('višina', models.IntegerField()),
                ('dolžina', models.IntegerField()),
                ('tip', models.BooleanField()),
                ('vtanka', models.IntegerField()),
                ('poraba', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='poraba',
        ),
        migrations.AddField(
            model_name='car',
            name='imgfile',
            field=models.ImageField(default=0, upload_to='images/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifikacije',
            name='ime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poraba.Car'),
        ),
    ]
