# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0002_auto_20170113_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='ime',
            new_name='serija',
        ),
    ]
