# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0003_auto_20170114_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serija', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Znamka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.TextField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='serija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poraba.Serija'),
        ),
        migrations.AlterField(
            model_name='car',
            name='znamka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poraba.Znamka'),
        ),
        migrations.AddField(
            model_name='serija',
            name='znamka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poraba.Znamka'),
        ),
    ]
