# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0004_auto_20170115_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifikacije',
            name='dolžina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specifikacije',
            name='tip',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='specifikacije',
            name='višina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specifikacije',
            name='vtanka',
            field=models.IntegerField(default=0),
        ),
    ]
