# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0005_auto_20170115_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifikacije',
            name='ime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poraba.Car'),
        ),
    ]
