# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poraba', '0007_auto_20170115_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifikacije',
            options={'permissions': (('add_car', 'Can add Car'),)},
        ),
    ]
