# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poraba', '0010_remove_specifikacije_poraba'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='car',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='znamka',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imgfile',
        ),
        migrations.RemoveField(
            model_name='car',
            name='serija',
        ),
        migrations.AddField(
            model_name='specifikacije',
            name='poraba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Serija',
        ),
        migrations.AddField(
            model_name='commentuser',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poraba.Car'),
        ),
        migrations.AddField(
            model_name='commentcar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poraba.Car'),
        ),
    ]
